// src/components/Background/Background.tsx
import { useEffect, useRef } from 'react';
import { buildBackground, init } from './konva/stage';
import { useAppState } from '@/store';

export function Background() {
  const backgroundRef = useRef<HTMLDivElement>(null);
  const setBackgroundRef = useAppState((state) => state.setBackgroundRef);

  useEffect(() => {
    init();
    buildBackground();

    let timeout: NodeJS.Timeout | undefined;
    window.addEventListener('resize', () => {
      clearTimeout(timeout);

      timeout = setTimeout(() => {
        buildBackground();
        timeout = undefined;
      }, 100);
    });
  });

  useEffect(() => {
    setBackgroundRef(backgroundRef);
  }, [setBackgroundRef]);

  return (
    <div
      ref={backgroundRef}
      className='fade-in opacity-0 absolute w-full h-full'
      id='container'
    />
  );
}

// src/lib/Background.svelte
<script>
  import { onMount } from 'svelte';
  import { buildBackground, init, setPause } from './konva/stage';

  onMount(() => {
    init();
    buildBackground();

    let to;
    window.addEventListener('resize', () => {
      clearTimeout(to);

      to = setTimeout(() => {
        buildBackground();
        to = undefined;
      }, 100);
    });
  });
</script>

<div class="opacity-0 absolute w-full h-full" id="container" />

<style>
  div {
    animation: fade-in;
    animation-duration: 900ms;
    animation-delay: 500ms;
    animation-fill-mode: forwards;
    animation-iteration-count: 1;
  }

  @keyframes fade-in {
    0% {
      opacity: 0;
    }
    100% {
      opacity: 1;
    }
  }
</style>
